GET http://localhost:3000/harjoitukset/

###
POST http://localhost:3000/harjoitukset/
Content-Type: application/json

{
    "pvm": "2023-01-02 14:30",
    "matka": 12.0,
    "syke": 125,
    "aika": 80
}

###
DELETE http://localhost:3000/harjoitukset/653529858b27eb5b95ba21d2